// Code generated by goctl. DO NOT EDIT.
// Source: user_mes.proto

package server

import (
	"context"

	"go-service/internal/pb"
	"go-service/service/user_mes/internal/logic/user_mes_model"
	"go-service/service/user_mes/internal/svc"
)

type UserMesModelServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserMesModelServer
}

func NewUserMesModelServer(svcCtx *svc.ServiceContext) *UserMesModelServer {
	return &UserMesModelServer{
		svcCtx: svcCtx,
	}
}

func (s *UserMesModelServer) GetUserMes(ctx context.Context, in *__.ReqID) (*__.User, error) {
	l := usermesmodellogic.NewGetUserMesLogic(ctx, s.svcCtx)
	return l.GetUserMes(in)
}

func (s *UserMesModelServer) PostUserMes(ctx context.Context, in *__.User) (*__.User, error) {
	l := usermesmodellogic.NewPostUserMesLogic(ctx, s.svcCtx)
	return l.PostUserMes(in)
}
