// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"go-service/service/article/internal/logic/author"
	"go-service/service/article/internal/svc"
	"go-service/service/pb/art"
)

type AuthorServer struct {
	svcCtx *svc.ServiceContext
	art.UnimplementedAuthorServer
}

func NewAuthorServer(svcCtx *svc.ServiceContext) *AuthorServer {
	return &AuthorServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthorServer) GetAuthor(ctx context.Context, in *art.Id) (*art.AuthorMesRes, error) {
	l := authorlogic.NewGetAuthorLogic(ctx, s.svcCtx)
	return l.GetAuthor(in)
}

func (s *AuthorServer) GetAuthorTotal(ctx context.Context, in *art.Empty) (*art.TotalRes, error) {
	l := authorlogic.NewGetAuthorTotalLogic(ctx, s.svcCtx)
	return l.GetAuthorTotal(in)
}
