version: "3"

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: article
    volumes:
      - ~/local-data/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - share-network

  redis:
    image: redis/redis-stack
    container_name: redis-stack
    restart: always
    volumes:
      - ~/local-data/redis/data:/data
      - ~/local-data/redis/logs:/logs
      - ~/local-data/redis/local-redis-stack.conf:/redis-stack.conf
    ports:
      - 6379:6379
      - 8001:8001

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: development
#      MONGO_INITDB_ROOT_PASSWORD: development
    volumes:
      - ~/local-data/mongodb/data:/data/db
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  share-network:
#    external: true
