// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"go-service/service/article/internal/logic"
	"go-service/service/article/internal/svc"
	"go-service/service/pb/art"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	art.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) GetServer(ctx context.Context, in *art.ArticleId) (*art.ArticleRes, error) {
	l := logic.NewGetServerLogic(ctx, s.svcCtx)
	return l.GetServer(in)
}

func (s *ArticleServer) PostServer(ctx context.Context, in *art.Article) (*art.ArticleRes, error) {
	l := logic.NewPostServerLogic(ctx, s.svcCtx)
	return l.PostServer(in)
}

func (s *ArticleServer) PutServer(ctx context.Context, in *art.ArticleRes) (*art.ArticleRes, error) {
	l := logic.NewPutServerLogic(ctx, s.svcCtx)
	return l.PutServer(in)
}

func (s *ArticleServer) DeleteServer(ctx context.Context, in *art.ArticleId) (*art.NilRes, error) {
	l := logic.NewDeleteServerLogic(ctx, s.svcCtx)
	return l.DeleteServer(in)
}
