// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"go-service/internal/pb"
	"go-service/service/product/internal/logic/product_model"
	"go-service/service/product/internal/svc"
)

type ProductModelServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedProductModelServer
}

func NewProductModelServer(svcCtx *svc.ServiceContext) *ProductModelServer {
	return &ProductModelServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductModelServer) GetProductModel(ctx context.Context, in *__.Empty) (*__.ViewProduct, error) {
	l := productmodellogic.NewGetProductModelLogic(ctx, s.svcCtx)
	return l.GetProductModel(in)
}
