Port: 8080
Host: "192.168.1.1"



MYSQL:
  Name: mysql
  Host: localhost
  Database: article
  Username: root
  Password: development
  Port: 3306
Redis:
  Name: redis
  Host: localhost
  Port: 6379
#yaml: this is a example of yaml