// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: service/user_mes.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReqID) Reset() {
	*x = ReqID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_mes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqID) ProtoMessage() {}

func (x *ReqID) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_mes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqID.ProtoReflect.Descriptor instead.
func (*ReqID) Descriptor() ([]byte, []int) {
	return file_service_user_mes_proto_rawDescGZIP(), []int{0}
}

func (x *ReqID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName     string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	SignedPerson int64  `protobuf:"varint,2,opt,name=signed_person,json=signedPerson,proto3" json:"signed_person,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_mes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_mes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_service_user_mes_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetSignedPerson() int64 {
	if x != nil {
		return x.SignedPerson
	}
	return 0
}

type UserArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *UserArr) Reset() {
	*x = UserArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_user_mes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserArr) ProtoMessage() {}

func (x *UserArr) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_mes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserArr.ProtoReflect.Descriptor instead.
func (*UserArr) Descriptor() ([]byte, []int) {
	return file_service_user_mes_proto_rawDescGZIP(), []int{2}
}

func (x *UserArr) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_service_user_mes_proto protoreflect.FileDescriptor

var file_service_user_mes_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62,
	0x22, 0x17, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x72, 0x72, 0x12,
	0x22, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x32, 0x6a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2b, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x12, 0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62, 0x2e, 0x72,
	0x65, 0x71, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x2b, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x1a, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x44, 0x62, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x42,
	0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_user_mes_proto_rawDescOnce sync.Once
	file_service_user_mes_proto_rawDescData = file_service_user_mes_proto_rawDesc
)

func file_service_user_mes_proto_rawDescGZIP() []byte {
	file_service_user_mes_proto_rawDescOnce.Do(func() {
		file_service_user_mes_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_user_mes_proto_rawDescData)
	})
	return file_service_user_mes_proto_rawDescData
}

var file_service_user_mes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_user_mes_proto_goTypes = []interface{}{
	(*ReqID)(nil),   // 0: testDb.reqID
	(*User)(nil),    // 1: testDb.user
	(*UserArr)(nil), // 2: testDb.user_arr
}
var file_service_user_mes_proto_depIdxs = []int32{
	1, // 0: testDb.user_arr.users:type_name -> testDb.user
	0, // 1: testDb.user_mes_model.get_user_mes:input_type -> testDb.reqID
	1, // 2: testDb.user_mes_model.post_user_mes:input_type -> testDb.user
	1, // 3: testDb.user_mes_model.get_user_mes:output_type -> testDb.user
	1, // 4: testDb.user_mes_model.post_user_mes:output_type -> testDb.user
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_user_mes_proto_init() }
func file_service_user_mes_proto_init() {
	if File_service_user_mes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_user_mes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_mes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_user_mes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_user_mes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_mes_proto_goTypes,
		DependencyIndexes: file_service_user_mes_proto_depIdxs,
		MessageInfos:      file_service_user_mes_proto_msgTypes,
	}.Build()
	File_service_user_mes_proto = out.File
	file_service_user_mes_proto_rawDesc = nil
	file_service_user_mes_proto_goTypes = nil
	file_service_user_mes_proto_depIdxs = nil
}
