// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "go-service/restful/art/internal/handler/article"
	author "go-service/restful/art/internal/handler/author"
	"go-service/restful/art/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: article.GetArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: article.PostArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: article.PutArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: author.GetAuthorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/total",
				Handler: author.GetArticleTotalHandler(serverCtx),
			},
		},
		rest.WithPrefix("/author"),
	)
}
