// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Type    *string `json:"type,optional"`
	Content *string `json:"content,optional"`
	Author  string  `json:"author"`
}

type ArticleRes struct {
	Article
	Id int64 `json:"id"`
}

type PathID struct {
	Id int64 `path:"id"`
}

type AuthorContent struct {
	Author       string `json:"author"`
	SignedPerson *bool  `json:"signedPerson,optional"`
	Cash         *int64 `json:"cash,optional"`
}

type AuthorRes struct {
	Authors []AuthorContent `json:"authors"`
	Id      int64           `json:"id"`
}

type AuthorTotal struct {
	Id       int64  `json:"id"`
	Author   string `json:"author"`
	Deleted  bool   `json:"deleted"`
	MesCount int64  `json:"mesCount"`
	CashSum  int64  `json:"cashSum"`
}

type NeedLived struct {
	Lived bool `json:"lived,optional"`
}

type TotalRes struct {
	AuthorTotals []AuthorTotal `json:"authorTotals"`
}
